spring:
  profiles: development
  cloud:
    stream:
      bindings:
        checkInQ:
          destination: checkInQ
          group: checkInQGroup
  datasource:
    url: jdbc:mysql://localhost:3306/brownfield-checkin-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
  session:
    store-type: redis
logging:
  level:
    root: info
    org.springframework.security: debug
    
    
---

spring:
  profiles: production
  cloud:
    stream:
      bindings:
        checkInQ:
          destination: checkInQ
          group: checkInQGroup
  datasource:
    url: jdbc:mysql://mysql-server/brownfield-checkin-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  redis:
    host: redis
  session:
    store-type: redis
logging:
  level:
    root: info
    org.springframework.security: info
