spring:
  profiles: development
  redis:
    host: localhost
  session:
    store-type: redis
logging:
  level:
    root: info
    org.springframework.security: debug
    
    
---


spring:
  profiles: production
  redis:
    host: redis
  session:
    store-type: redis
logging:
  level:
    root: info
    org.springframework.security: info    
