spring:
  profiles: development
  redis:
    host: localhost
  session:
    store-type: redis
zuul:
  routes:
    fare-service:
      path: /fare-service/**
      url: http://localhost:8080/
      sensitive-headers: 
    checkin-service:
      path: /checkin-service/**
      url: http://localhost:8070/
      sensitive-headers: 
    search-service:
      path: /search-service/**
      url: http://localhost:8090/
      sensitive-headers: 
    booking-service:
      path: /booking-service/**
      url: http://localhost:8060/
      sensitive-headers: 
    ui-service:
      path: /ui-service/**
      url: http://localhost:8001/
      sensitive-headers:
logging:
  level:
    root: info
    org.springframework.security: debug
info:
  app:
    name: Spring Boot Zuul Proxy System
    description: This application is a reverse proxy
    version: 1.0    
    
    
---

spring:
  profiles: production
  redis:
    host: redis
  session:
    store-type: redis
zuul:
  routes:
    fare-service:
      path: /fare-service/**
       sensitive-headers: 
    checkin-service:
      path: /checkin-service/**
      sensitive-headers: 
    search-service:
      path: /search-service/**
      sensitive-headers: 
    booking-service:
      path: /booking-service/**
      url: http://localhost:8060/
      sensitive-headers: 
    ui-service:
      path: /ui-service/**
      sensitive-headers:
logging:
  level:
    root: info
    org.springframework.security: info
info:
  app:
    name: Spring Boot Zuul Proxy Production System
    description: This application is a reverse proxy
    version: 1.0    
