spring:
  cloud:
    stream:
      bindings:
        searchQ:
          destination: searchQ
          group: searchQGroup
  datasource:
    url: jdbc:mysql://localhost:3306/brownfield-search-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
originairports:
  shutdown: SEA
