spring:
  profiles: development
  cloud:
    stream:
      bindings:
        searchQ:
          destination: searchQ
          group: searchQGroup
  datasource:
    url: jdbc:mysql://localhost:3306/brownfield-search-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
originairports:
  shutdown: SEA
logging:
  level:
    root: info
    org.springframework.security: debug
    
---

spring:
  profiles: production
  cloud:
    stream:
      bindings:
        searchQ:
          destination: searchQ
          group: searchQGroup
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER}/brownfield-search-service?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_MASTER}
originairports:
  shutdown: SEA
logging:
  level:
    root: info
    org.springframework.security: info
